
<h1>Exemplo de listas.</h1>
<a href="<?= $this->url('modulo',['action'=>'add']); ?>" class='btn btn-primary'> Add</a>
<table class="table table-stripped">
    <tr>
        <th>Codigo</th>
        <th>Valor</th>
        <th>Dados de Registro</th>
    </tr>
<hr>
<?php
    foreach($modulo as $key => $value){
            ?>
                <tr>
                    <td><?= $value->getId(); ?></td>
                    <td><?= $value->getValor(); ?></td>
                    <td><?= $value->getDataRegistro(); ?></td>
                    <td><a href="<?= $this->url('modulo',['action' => 'edit','id' => $value->getId()]); ?>" class="btn btn-info"><i class="glyphicon glyficon-edit"></i></a></td>                    
                </tr>
            <?php
    }
?>
</table>