
<h1>Exemplo de listas.</h1>
<table class="table table-stripped">
    <tr>
        <th>Codigo</th>
        <th>Valor</th>
        <th>Data Registro</th>
    </tr>
<hr>
<?php
    foreach($modulo as $key => $value){
            ?>
                <tr>
                    <td><?= $value->getId(); ?></td>
                    <td><?= $value->getValor(); ?></td>
                    <td><?= $value->getDataRegistro(); ?></td>
                </tr>
            <?php
    }
?>
</table>