version: "3.0"
networks:
  backend:
services:  
  php:
    build:
      dockerfile: php7-runner.dockerfile 
      context: .
    image: 'laravelapp'
    ports:
      - "80:80"
      - "443:443"
    volumes:            
      - ./:/var/www/html       
    links:
      - mysql
    networks:
      - backend
    depends_on:
      - mysql    
  mysql:
    restart: always
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phprs
      - MYSQL_DATABASE=phprs
    networks:
      - backend