version: "3.0"
services:  
  php:
    image: php:7.3-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html
      - .:/var/www/
      - ./apache/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./apache/.htaccess:/var/www/html/.htaccess
    links:
      - mysql    
  mysql:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phprs
      - MYSQL_DATABASE=phprs